### ISSUE TITLE
Hotger

### ISSUE THREAD

**Issue by Inna333666** [AlexandrPeshkov/ZigZag#4]
Александр, привет, меня зовут Инна Остапенко и я HR менеджер компании Hotger. Мы делаем игры и галопирующими темпами развиваемся. Как ты понимаешь, для разработки игр мне очень нужны дельные разработчики. Мои технические спецы посмотрели твой код и оценили его качество очень положительно, а от них такое не каждый услышит:)
К сожалению, кроме как таким образом больше никак с тобой связаться не могу.
В электронной визитке все мои контакты, я буду просто счастлива, если ты мне напишешь на почту или в телеграмм.
Спасибо тебе заранее,
Инна Остапенко
HR Менеджер
Hotger Corporation
тел: +7 918 522 5310
telegram: @Ostapenko_Inna
e-mail: inna.ostapenko@hotger.com
сайт: www.hotger.com

**Comment by AlexandrPeshkov** [comment]
Добрый день, было неожиданно увидеть от HR сообщение в GitHib :D Благодарю
за отзыв о коде)
В телеграм по номеру не удалось написать, поэтому письмом. tg -
@AlexandrPeshkov.
Поиск и возможный  переход в другую компанию рассматривал не раньше мая. Но
раз меня нашли первей, то давайте пообщаемся детальнее в tg, прикладываю
резюме.

ср, 24 мар. 2021 г. в 14:52, Inna ***@***.***>:
